version: '3.8'

services:
  web:
    build: ./app
    command: python /app/main.py
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
